# -*- coding: utf-8 -*-
"""Deep_learning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_SzXXy-hfYIsMyTyCLv0jPJdnqcBwOeS
"""

# Configuration de l'accès à Kaggle
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json
!pip install -q kaggle

# Téléchargement et extraction du dataset
!kaggle datasets download -d asdasdasasdas/garbage-classification
!unzip -q garbage-classification.zip -d dataset

import tensorflow as tf
print("GPU disponible :", tf.config.list_physical_devices('GPU'))

# Tous les imports dont on aura besoin pour la suite
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras import layers, models

base_path = "dataset/garbage classification/Garbage classification"
taille_image = (224, 224)
taille_batch = 32

train_ds = tf.keras.utils.image_dataset_from_directory(
    base_path,
    validation_split=0.2,
    subset="training",
    seed=123,
    image_size=taille_image,
    batch_size=taille_batch
)

val_ds = tf.keras.utils.image_dataset_from_directory(
    base_path,
    validation_split=0.2,
    subset="validation",
    seed=123,
    image_size=taille_image,
    batch_size=taille_batch
)

noms_classes = train_ds.class_names
print("Classes détectées :", noms_classes)

AUTOTUNE = tf.data.AUTOTUNE
train_ds = train_ds.cache().shuffle(1000).prefetch(buffer_size=AUTOTUNE)
val_ds = val_ds.cache().prefetch(buffer_size=AUTOTUNE)

base_model = MobileNetV2(
    input_shape=(224, 224, 3),
    include_top=False,
    weights="imagenet"
)
base_model.trainable = False

model = models.Sequential([
    layers.Input(shape=(224, 224, 3)),
    layers.Rescaling(1./127.5, offset=-1),
    base_model,
    layers.GlobalAveragePooling2D(),
    layers.Dropout(0.2),
    layers.Dense(6, activation="softmax")
])
model.summary()

model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

# On récupère la liste des noms de classes détectées automatiquement
# (l'ordre correspond à l'ordre alphabétique des dossiers : cardboard, glass, metal, paper, plastic, trash)
noms_classes = train_ds.class_names
print("Classes détectées :", noms_classes)

# On optimise le chargement des données pour que ça n'attende pas le disque pendant l'entraînement
# (technique standard recommandée par TensorFlow, transparente pour toi)
AUTOTUNE = tf.data.AUTOTUNE
train_ds = train_ds.cache().shuffle(1000).prefetch(buffer_size=AUTOTUNE)
val_ds = val_ds.cache().prefetch(buffer_size=AUTOTUNE)

historique = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=10
)

# Sauvegarde du modèle entraîné dans un fichier .h5
model.save("modele_eco_sort.h5")
print("Modèle sauvegardé avec succès !")





